
services:
  db:
    image: mysql:8.0
    container_name: bfe_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-bfe_db}
      MYSQL_USER: ${MYSQL_USER:-symfony}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 6

  php:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: bfe_php
    depends_on:
      db:
        condition: service_healthy
    environment:
      APP_ENV: prod
      APP_DEBUG: "0"
      DATABASE_URL: "mysql://${MYSQL_USER:-symfony}:${MYSQL_PASSWORD:-password}@db:3306/${MYSQL_DATABASE:-bfe_db}?serverVersion=8.0&charset=utf8mb4&ssl-mode=DISABLED"

      MAILER_DSN: "${MAILER_DSN}"
      MAILER_FROM: "${MAILER_FROM}"


    volumes:
      - jwt_keys:/var/www/app/config/jwt
    healthcheck:
      test: ["CMD-SHELL", "php -v >/dev/null 2>&1 && php -r 'echo 1;'"]
      interval: 30s
      timeout: 10s
      retries: 6

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: bfe_worker
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      APP_ENV: prod
      APP_DEBUG: "0"
      DATABASE_URL: "mysql://${MYSQL_USER:-symfony}:${MYSQL_PASSWORD:-password}@db:3306/${MYSQL_DATABASE:-bfe_db}?serverVersion=8.0&charset=utf8mb4&ssl-mode=DISABLED"

      MAILER_DSN: "${MAILER_DSN}"
      MAILER_FROM: "${MAILER_FROM}"



    command: >
      sh -lc "
        php bin/console messenger:setup-transports --no-interaction &&
        exec php bin/console messenger:consume async -vv --sleep=1 --memory-limit=256M
      "

  web:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: bfe_web
    depends_on:
      php:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/healthz"]
      interval: 30s
      timeout: 5s
      retries: 6

volumes:
  mysql_data:
  jwt_keys:
