nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:4200', 'http://127.0.0.1:4200']
        allow_credentials: true
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
        max_age: 3600
    paths:
        '^/api/':
            origin_regex: true
            allow_origin: ['http://localhost:4200', 'http://127.0.0.1:4200']
            allow_credentials: true
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
